# Slicing
[start:stop:step]

In [1]:
import numpy as np

In [2]:
lists=[1,2,3,5,8,9,6,7]
lists[1:5]

[2, 3, 5, 8]

In [3]:
lists[1:7:2]

[2, 5, 9]

In [4]:
arr=np.array(lists)
arr

array([1, 2, 3, 5, 8, 9, 6, 7])

In [5]:
arr[1:7:2]

array([2, 5, 9])

In [6]:
# multi-dimensional

In [7]:
lists=[[1,2,3,4,5],[4,5,6,4,8]]

In [8]:
lists[0][3:]

[4, 5]

In [9]:
arr=np.array(lists)
arr

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 4, 8]])

In [10]:
arr[0][3:]

array([4, 5])

In [11]:
arr[0,3:]

array([4, 5])

In [12]:
arr[:,1:4]

array([[2, 3, 4],
       [5, 6, 4]])

In [13]:
lists=[[1,2,3,4,5,6,7,8],[1,3,5,7,9,11,13,15]]
arr=np.array(lists)

In [14]:
a1=arr[0,1:8:2]

In [15]:
a2=arr[1,0:8:2]

In [16]:
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 1,  3,  5,  7,  9, 11, 13, 15]])

In [17]:
arr[:,1:9:2]

array([[ 2,  4,  6,  8],
       [ 3,  7, 11, 15]])

In [18]:
a2=(arr.reshape(16))
a2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  1,  3,  5,  7,  9, 11, 13, 15])

In [19]:
lists=[[1,2,3,4,5,6,7,8],[1,3,5,7,9,11,13,15],[79,4,6,4,64,88,1216,878]]

In [20]:
a1=np.array(lists)
a1

array([[   1,    2,    3,    4,    5,    6,    7,    8],
       [   1,    3,    5,    7,    9,   11,   13,   15],
       [  79,    4,    6,    4,   64,   88, 1216,  878]])

In [21]:
a1[1:3,4:7]

array([[   9,   11,   13],
       [  64,   88, 1216]])

In [22]:
a1.shape

(3, 8)

In [23]:
a1.shape[0]+1

4

In [24]:
lists=[[[1,2,3,4],[4,59,61,1]],[[1,5,6,8],[7,8,9,6]]]
lists=np.array(lists)

In [25]:
lists.ndim

3

In [26]:
lists.shape

(2, 2, 4)

In [27]:
lists[:,:,1:3]

array([[[ 2,  3],
        [59, 61]],

       [[ 5,  6],
        [ 8,  9]]])

# Methods and attribute

In [37]:
# Attribute

In [38]:
a=np.array([[1,2,3],[4,5,6]])
a.shape

(2, 3)

In [39]:
a.ndim

2

In [40]:
a.dtype

dtype('int32')

In [41]:
# Method

In [42]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [43]:
a.sum()

21

In [44]:
a.max()

6

In [51]:
# axis=0 (column)
# axis=1 (row)

In [48]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
a.max(axis=0)

array([4, 5, 6])

In [50]:
a.max(axis=1)

array([3, 6])

In [52]:
a.argmax(axis=1)

array([2, 2], dtype=int64)

In [53]:
a.argmax(axis=0)

array([1, 1, 1], dtype=int64)

In [54]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
a.shape

(2, 3)

In [57]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [60]:
a.reshape(1,2,3)

array([[[1, 2, 3],
        [4, 5, 6]]])

In [68]:
a1=np.array([[1,2,3],[4,5,6]])
a2=np.array([[5,4,3],[7,9,2]])
np.concatenate((a1,a2), axis=None)

array([1, 2, 3, 4, 5, 6, 5, 4, 3, 7, 9, 2])

In [65]:
np.concatenate((a1,a2), axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [5, 4, 3],
       [7, 9, 2]])

In [66]:
np.concatenate((a1,a2), axis=1)

array([[1, 2, 3, 5, 4, 3],
       [4, 5, 6, 7, 9, 2]])

In [85]:
a=a.reshape(6)
a

array([1, 2, 3, 4, 5, 6])

In [86]:
np.split(a,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [89]:
np.split(a,[2,5,7])

[array([1, 2]), array([3, 4, 5]), array([6]), array([], dtype=int32)]