In [1]:
import numpy as np

# Create array

## 1D array

In [2]:
list=[1,2,'abc']
arr1=np.array(list) #use same datatype for array conversion
arr1

array(['1', '2', 'abc'], dtype='<U11')

# np.arange()
(range(start,stop, step)) -----> one and only single dimension

In [3]:
arr2=np.arange(5)
arr2

array([0, 1, 2, 3, 4])

In [4]:
arr2=np.arange(5,14)
arr2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13])

In [5]:
arr2=np.arange(5,14,3)
arr2

array([ 5,  8, 11])

# np.zeros()

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

# np.ones()

In [7]:
np.ones(4)

array([1., 1., 1., 1.])

# np.full()

In [8]:
np.full(4,3)

array([3, 3, 3, 3])

# np.linspace()
np.linspace(start,stop, total number of elements)

In [9]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# np.random.rand()
value between 0 and 1

In [10]:
np.random.rand(5)

array([0.12215728, 0.27811891, 0.26671829, 0.74061013, 0.0881543 ])

# np.random.randint(start,stop,dimension)

In [11]:
np.random.randint(5)

0

In [12]:
np.random.randint(5,14)

6

In [13]:
np.random.randint(1,4,5)

array([3, 3, 1, 1, 2])

In [14]:
np.random.randint(2,11,size=(4,3))

array([[ 2,  8,  6],
       [ 4, 10,  5],
       [10, 10,  5],
       [10,  4,  2]])

## 2D array

In [15]:
list=[[1,2,3],[7,8,9]]
arr1=np.array(list) 
print(arr1)
print(type(arr1))
print(arr1.ndim)

[[1 2 3]
 [7 8 9]]
<class 'numpy.ndarray'>
2


In [16]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.full((2,3),-6)

array([[-6, -6, -6],
       [-6, -6, -6]])

In [19]:
np.linspace((1,10),(5,11),7)

array([[ 1.        , 10.        ],
       [ 1.66666667, 10.16666667],
       [ 2.33333333, 10.33333333],
       [ 3.        , 10.5       ],
       [ 3.66666667, 10.66666667],
       [ 4.33333333, 10.83333333],
       [ 5.        , 11.        ]])

In [20]:
np.linspace((1,10),(5,11),num=7)      # key can be passed

array([[ 1.        , 10.        ],
       [ 1.66666667, 10.16666667],
       [ 2.33333333, 10.33333333],
       [ 3.        , 10.5       ],
       [ 3.66666667, 10.66666667],
       [ 4.33333333, 10.83333333],
       [ 5.        , 11.        ]])

# np.diag()
not for 1D

differ in matrix size

In [21]:
np.diag([2,3])

array([[2, 0],
       [0, 3]])

In [22]:
np.diag([2,3,5])

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [23]:
np.diag([2,3,5],2)

array([[0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 5],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [24]:
np.diag([2,3,5],k=-2)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [2, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 5, 0, 0]])

# np.identity()
not for 1D

In [25]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# np.eye()
not for 1D

same matrix size

In [26]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
np.eye(5,k=2)   # only k can be used

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
np.eye(5,k=-2)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [29]:
np.random.rand(4,5)

array([[0.76044703, 0.03182314, 0.77592125, 0.09539178, 0.05182061],
       [0.89084786, 0.61808034, 0.54596838, 0.10977498, 0.79011142],
       [0.19039132, 0.86812259, 0.08366629, 0.48677817, 0.52587877],
       [0.06633363, 0.99671182, 0.20387256, 0.29427269, 0.02178024]])

In [30]:
np.random.randint(2,11,size=(4,3))

array([[2, 9, 9],
       [2, 6, 2],
       [9, 9, 9],
       [4, 7, 9]])

# Multiple dimension

In [31]:
arr1=np.ones((4,3,2))
arr1

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [32]:
np.full((4,3,5),-8)

array([[[-8, -8, -8, -8, -8],
        [-8, -8, -8, -8, -8],
        [-8, -8, -8, -8, -8]],

       [[-8, -8, -8, -8, -8],
        [-8, -8, -8, -8, -8],
        [-8, -8, -8, -8, -8]],

       [[-8, -8, -8, -8, -8],
        [-8, -8, -8, -8, -8],
        [-8, -8, -8, -8, -8]],

       [[-8, -8, -8, -8, -8],
        [-8, -8, -8, -8, -8],
        [-8, -8, -8, -8, -8]]])

In [33]:
arr1.reshape(24)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1.])

# INDEXING

In [34]:
lists=[1,2,3]
lists[2]

3

In [35]:
lists=[[1,2,3],[4,5,6]]
lists[0][1]

2

In [36]:
arr1=np.array(lists)

In [37]:
arr1[0][1]

2

In [38]:
arr1[0,1]

2