In [1]:
import numpy as np

In [2]:
# dtype= np.int32, np.float64, dtype=np.bool_

# int= from 8
# float= from 16
# complex= from 64

a=np.array([1,2,3],dtype=np.float32)
b=np.array([1.1,0,-3.1],dtype=np.bool_)
c=np.array([True,False,True],dtype=np.int32)
print(a.dtype)
print(b.dtype)
print(c.dtype)
print(c)
print(b)

float32
bool
int32
[1 0 1]
[ True False  True]


In [3]:
# astype (for float conversion)

In [4]:
a.dtype

dtype('float32')

In [5]:
a=a.astype(np.int32)
print(a)
a.dtype

[1 2 3]


dtype('int32')

In [6]:
import numpy as np

In [7]:
a=np.array([4,5,6],dtype=np.int32)
a

array([4, 5, 6])

In [8]:
a.dtype

dtype('int32')

In [9]:
a=a.astype(np.float32)
a.dtype

dtype('float32')

# Operation

In [10]:
# Elementwise operation (Individual Element)

In [11]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[9,8,7],[1,5,9]])

In [12]:
a+b

array([[10, 10, 10],
       [ 5, 10, 15]])

In [13]:
a%b

array([[1, 2, 3],
       [0, 0, 6]])

In [14]:
np.add(a,b)

array([[10, 10, 10],
       [ 5, 10, 15]])

In [15]:
a=np.array([1.1,5.5,4.6])
np.floor(a)

array([1., 5., 4.])

In [16]:
np.ceil(a)

array([2., 6., 5.])

In [17]:
np.round(a)

array([1., 6., 5.])

In [18]:
b=np.transpose(b)

In [19]:
np.dot(a,b)

array([86.1, 70. ])

In [20]:
a

array([1.1, 5.5, 4.6])

In [22]:
a=np.array([[1,2,3],[4,5,6]])
np.trace(a) # add diagonal element

6

In [23]:
a=np.array([[2,3],[5,4]])
a

array([[2, 3],
       [5, 4]])

In [24]:
np.linalg.det(a)

-6.999999999999999

In [25]:
np.linalg.inv(a)

array([[-0.57142857,  0.42857143],
       [ 0.71428571, -0.28571429]])

In [26]:
np.linalg.eig(a)

(array([-1.,  7.]),
 array([[-0.70710678, -0.51449576],
        [ 0.70710678, -0.85749293]]))

In [27]:
a=[[1,2],[3,5]]
b=[2,3]
np.linalg.solve(a,b)

array([-4.,  3.])

In [28]:
a=np.array([[1,2],[3,4]])

In [29]:
np.linalg.eig(a)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [30]:
# Broadcasting

In [31]:
a=np.array([[1,2],[6,4],[4,6]])
b=np.array([10,20])

In [32]:
a+b

array([[11, 22],
       [16, 24],
       [14, 26]])

In [33]:
# Masking

In [34]:
y = np.array([[1,2],[3,4],[5,6]])
mask = np.array([[True, False], [True, True],[True, False]])
y[mask]

array([1, 3, 4, 5])

In [35]:
cond_mask = (y>2)  # y is array 
y[cond_mask]

array([3, 4, 5, 6])