# Perceptron

In [1]:
import numpy as np

In [2]:
class Perceptron:
    def __init__(self, num_features):
        self.num_features = num_features
        self.weights = np.zeros(num_features)
        self.bias = 0
        self.activation_function = lambda x: 1 if x >= 0 else 0

    def predict(self, x):
        linear_output = np.dot(self.weights, x) + self.bias
        print(np.dot(self.weights, x)+ self.bias)
        return self.activation_function(linear_output)

In [3]:
# Create a perceptron with 2 input features and using the step function as the activation function
perceptron = Perceptron(2)

# Set the weights and bias
perceptron.weights = np.array([0.5, -0.5])
perceptron.bias = 0.2

# Make predictions
x = np.array([0.3, -0.7])
prediction = perceptron.predict(x)
print("Perceptron prediction:", prediction)

0.7
Perceptron prediction: 1


# MLP (Multi Layer Perceptron)

In [4]:
class MLP:
    def __init__(self, input_size, hidden_sizes, output_size, activation='sigmoid'):
        self.input_size = input_size
        self.hidden_sizes = hidden_sizes
        self.output_size = output_size

        self.weights = []
        self.biases = []

        layer_sizes = [input_size] + hidden_sizes + [output_size]
        print(layer_sizes)

        for i in range(len(layer_sizes) - 1):
            weight_matrix = np.random.randn(layer_sizes[i], layer_sizes[i+1])
            self.weights.append(weight_matrix)
            bias_vector = np.zeros(layer_sizes[i+1])
            print(layer_sizes[i+1])
            print("----------------")
            print(bias_vector)
            print("-------------")
            self.biases.append(bias_vector)
        
        print(self.weights)
        print(self.biases)

        if activation == 'sigmoid':
            self.activation_function = self._sigmoid
        elif activation == 'tanh':
            self.activation_function = self._tanh
        elif activation == 'relu':
            self.activation_function = self._relu
        else:
            raise ValueError("Unsupported activation function.")

    def forward(self, x):
        activations = [x]

        for i in range(len(self.weights)):
            linear_output = np.dot(activations[-1], self.weights[i]) + self.biases[i]
            print("************* hey")
            print(linear_output)
            print(activations[-1])
            print("////////////////finish")
            output = self.activation_function(linear_output)
            activations.append(output)

        return activations[-1]

    def _sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def _tanh(self, x):
        return np.tanh(x)

    def _relu(self, x):
        return np.maximum(0, x)

In [5]:
# Example usage
mlp = MLP(input_size=4, hidden_sizes=[8, 6], output_size=3, activation='sigmoid')
input_data = np.random.randn(10, 4)  # Example input data with 10 samples
output = mlp.forward(input_data)  # Compute the MLP's output
print(output)
print("********************")
print(np.random.randn(10, 4))

[4, 8, 6, 3]
8
----------------
[0. 0. 0. 0. 0. 0. 0. 0.]
-------------
6
----------------
[0. 0. 0. 0. 0. 0.]
-------------
3
----------------
[0. 0. 0.]
-------------
[array([[-0.49524029,  1.88981953, -0.51382169, -0.02348304,  1.47076002,
        -1.01001069,  2.07349417,  0.01511628],
       [ 0.7326151 , -0.17311577,  0.65140944,  2.01805801, -1.47546763,
         0.9704011 , -1.94126797, -1.65907008],
       [-1.38153925, -1.39201252,  1.35145324,  1.81354106,  0.43543916,
        -0.6844334 , -1.07487883, -2.97702599],
       [ 0.62863966,  0.0107043 ,  0.21020409, -0.01131568, -0.27206221,
        -1.00073937,  0.01472577,  1.37963309]]), array([[ 0.48405106,  1.18495779, -0.44263087, -0.45964798,  1.48800607,
         0.51703048],
       [ 1.81630233, -1.72326383, -1.1016762 , -0.20249709, -0.87392201,
         2.09056889],
       [-1.16235478, -0.54037351,  0.14062633, -0.3928467 , -0.2192747 ,
        -1.09303296],
       [ 0.11730326,  0.53536662, -1.11335479, -0.27114656,

# Backpropagation

In [6]:
class MLP:
    def __init__(self, input_size, hidden_size, output_size):
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size

        # Initialize weights with random values
        self.W1 = np.random.randn(input_size, hidden_size)
        self.W2 = np.random.randn(hidden_size, output_size)

#          # Initialize bases with random values
#         self.b1 = np.random.randn(hidden_size)
#         self.b2 = np.random.randn(output_size)
        
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def sigmoid_derivative(self, x):
        return x * (1 - x)

    def forward(self, X):
        self.hidden_layer = self.sigmoid(np.dot(X, self.W1)) # + self.b1)
        self.output_layer = self.sigmoid(np.dot(self.hidden_layer, self.W2)) # + self.b2)

    def backward(self, X, y, learning_rate):
        # Calculate the gradients
        output_error = y - self.output_layer
        output_delta = output_error * self.sigmoid_derivative(self.output_layer)
        hidden_error = output_delta.dot(self.W2.T)
        hidden_delta = hidden_error * self.sigmoid_derivative(self.hidden_layer)

        # Update the weights
        self.W2 -= self.hidden_layer.T.dot(output_delta) * learning_rate
        self.W1 -= X.T.dot(hidden_delta) * learning_rate
        
#         self.b2 -= self.hidden_layer.T.dot(output_delta) * learning_rate
#         self.b1 -= X.T.dot(hidden_delta) * learning_rate

    def train(self, X, y, epochs=1000, learning_rate=0.01):
        for epoch in range(epochs):
            self.forward(X)
            self.backward(X, y, learning_rate)

    def predict(self, X):
        self.forward(X)
        return self.output_layer

In [7]:
# Training data
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

# Create an MLP object
mlp = MLP(input_size=2, hidden_size=4, output_size=1)

# Train the MLP
mlp.train(X, y, epochs=10000, learning_rate=0.1)

# Test the MLP
predictions = mlp.predict(X)

In [8]:
print(predictions)

[[0.99906576]
 [0.9999866 ]
 [0.99699844]
 [0.99995018]]


In [9]:
a=np.random.randn(10, 4)
print(a)

[[-0.31771213  0.80840607 -0.34387517  0.50924612]
 [ 2.06458092  1.73093796 -1.17949759  0.46595452]
 [-0.34461268  1.77095402 -1.07589665  0.28492606]
 [-0.5562792   0.94660084  0.56094874 -1.02139304]
 [ 0.56108371 -1.13273055  0.59444631  1.01363462]
 [ 1.0540316  -1.35319818 -0.61147083  1.69883598]
 [ 1.27366367  0.45211117  0.87344654 -0.17615236]
 [-0.12806607 -1.49915707 -0.2686678  -0.68117001]
 [-0.64220631  2.50910649 -0.03547154 -1.5774031 ]
 [-0.39907123  0.48624918 -0.63709872  0.54964787]]


In [10]:
print(a[-1])

[-0.39907123  0.48624918 -0.63709872  0.54964787]


In [11]:
for i in range(3):
    print (i)

0
1
2
